# Docker compose version
version: '3'
# Type of services that are created: The flask apps created the folder they are placed in under build and the ports that we have exposed them to
services:
  flask_app_1:
    build: ./flask1
    ports:
      - "5005:5000"
    volumes:
      - ./flask1:/app
  flask_app_2:
    build: ./flask2
    ports:
      - "8008:5000"
    volumes:
      - ./flask2:/app
