version: '3' ##version 3 syntax not the main version of docker##
services:
  flask_app_1:
    build: ./flask1
    ports:
      - "5001:5000"
    volumes:
      - ./flask1:/app
  flask_app_2:
    build: ./flask2
    ports:
      - "8002:5000"
    volumes:
      - ./flask2:/app
